#!/bin/bash

set -e
export -n PLATFORMIO_AUTH_TOKEN
#python3 -m platformio test -e native 
#python3 -m platformio run -t upload -e sparkfun_promicro16
python3 -m platformio remote run -t upload -e sparkfun_promicro16


mosquitto_pub -h demeter -r -t 'maoam/permits' -m 1
mosquitto_pub -h demeter -r -t 'rfid/card' -m 0

